### ISSUE TITLE
antlr version mismatch 4.6!=4.5.3

### ISSUE THREAD

**Issue by ekolve** [hfoffani/pddl-lib#14]
The current wheel hosted on pypi https://pypi.python.org/packages/82/89/b3691af31bfca356028d48866ab1d74a47b8746cdc2359dea7d7b3a3db6b/pddlpy-0.1.6-py3-none-any.whl#md5=321525a511519d47652bf2f72e3770aa was built using antlr 4.5.3.  Following the instructions in the README or just running brew upgrade will install the latest antlr 4.6.  When running pddlpy a warning will get generated:

ANTLR runtime and generated code versions disagree: 4.6 != 4.5.3

This doesn't seem to cause any actual issues with the code that I can see.  I resolved the issue by cloning, editing the Makefile, running make pyparsers, then python setup.py install.

**Comment by hfoffani** [comment]
Sorry for the delay.

You are correct. I upgraded to 4.6 (although Antlr is now at 4.7, brew didn't upgraded to that yet) and fixed setup.py to look after 4.6 exclusively.
