### ISSUE TITLE
negative preconditions example

### ISSUE THREAD

**Issue by ekolve** [hfoffani/pddl-lib#8]
Are negative preconditions supposed to work? I tried changing the move action in domain-03.pddl to:

```
 (:action move
     :parameters (?r - robot ?from ?to - location)
     :precondition (and (adjacent ?from ?to) (not (atl ?r ?from)) )
     :effect (and (atl ?r ?to)
                    (not (atl ?r ?from)) ))
```

And precondition_pos is still returning 

```
{('atl', '?r', '?from'), ('adjacent', '?from', '?to')}
```

**Comment by hfoffani** [comment]
Yes :-(
It seems to be a bug there, sorry.
I will try to fix it.

**Comment by hfoffani** [comment]
Oh sorry. I forgot that my focus was to implement STRIPS.

The parser does not fail as it is prepared for future enhancements. That is confusing for the user, sure. The fact that it does not report unimplemented features definitely _is_ a bug.

Anyway, this non-strips feature would probably the easiest to implement.

**Comment by hfoffani** [comment]
I have deployed a new Python version that fixes the negative preconditions. The sources are here in github and in PyPI (version 0.1.6)

I hope you find it useful. Thanks!

_I have not test it for .NET yet._

**Comment by ekolve** [comment]
Thank you! Works great!
